version: '3.9'

services:
  db:
    image: postgres:17
    container_name: standard_db
    ports:
      - 8080:5432
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.4.1-alpine
    container_name: standard_redis
    ports:
      - 8081:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  redis_data:

