// Code generated by SQL-to-Model generator.
package models

import (
	"time"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type District struct {
	ID        uuid.UUID       `gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	Version   int             `gorm:"type:integer;not null;default:0"`
	CreatedAt time.Time       `gorm:"type:timestamp;not null;default:now()"`
	CreatedBy *uuid.UUID      `gorm:"type:uuid"`
	UpdatedAt time.Time       `gorm:"type:timestamp;not null;default:now()"`
	UpdatedBy *uuid.UUID      `gorm:"type:uuid"`
	DeletedAt *gorm.DeletedAt `gorm:"type:timestamp"`

	NameTh string `gorm:"type:varchar(100);not null"`
	NameEn string `gorm:"type:varchar(100);not null"`

	ProvinceID uuid.UUID `gorm:"type:uuid;column:province_id"`

	Province *Province `gorm:"foreignKey:ProvinceID;references:ID"`
	SubDistricts []SubDistrict `gorm:"foreignKey:DistrictID"`
	Addresses []Address `gorm:"foreignKey:DistrictID"`
}

func (r *District) BeforeUpdate(tx *gorm.DB) (err error) {
	r.Version++
	return
}
