// Code generated by SQL-to-Model generator.
package models

import (
	"github.com/wisaitas/standard-golang/pkg"
)

type Province struct {
	pkg.BaseModel
	NameTH string `gorm:"column:name_th;"`
	NameEN string `gorm:"column:name_en;"`
}
