// Code generated by SQL-to-Model generator.
package models

import (
	"github.com/google/uuid"
	"github.com/wisaitas/standard-golang/pkg"
	"gorm.io/gorm"
)

type SubDistrict struct {
	pkg.BaseModel

	NameTH     string `gorm:"column:name_th;"`
	NameEN     string `gorm:"column:name_en;"`
	PostalCode string `gorm:"column:postal_code;"`

	DistrictID uuid.UUID `gorm:"column:district_id;"`

	District *District `gorm:"foreignKey:DistrictID;references:ID"`
}

func (r *SubDistrict) BeforeUpdate(tx *gorm.DB) (err error) {
	r.Version++
	return
}
