// Code generated by SQL-to-Model generator.
package models

import (
	"time"

	"github.com/wisaitas/standard-golang/pkg"
)

type UserHistory struct {
	pkg.BaseModel

	Action       string    `gorm:"type:user_action;not null;comment:enum type"`
	OldVersion   int       `gorm:"type:integer;not null"`
	OldFirstName string    `gorm:"type:varchar(100);not null"`
	OldLastName  string    `gorm:"type:varchar(100);not null"`
	OldBirthDate time.Time `gorm:"type:date;not null"`
	OldPassword  string    `gorm:"type:varchar(100);not null"`
	OldEmail     string    `gorm:"type:varchar(100);not null"`
}
